# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='educationalBackground_Info',
            fields=[
                ('student_info_id', models.TextField(primary_key=True, serialize=False)),
                ('elementary_name', models.CharField(max_length=100)),
                ('elementary_address', models.CharField(max_length=100)),
                ('elementary_dates', models.CharField(max_length=20)),
                ('elementary_awards', models.CharField(max_length=100)),
                ('highschool_name', models.CharField(max_length=100)),
                ('highschool_address', models.CharField(max_length=100)),
                ('highschool_dates', models.CharField(max_length=20)),
                ('highschool_awards', models.CharField(max_length=100)),
                ('vocational_name', models.CharField(max_length=100)),
                ('vocational_address', models.CharField(max_length=100)),
                ('vocational_course', models.CharField(max_length=100)),
                ('vocational_dates', models.CharField(max_length=20)),
                ('vocational_awards', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('college_address', models.CharField(max_length=100)),
                ('college_course', models.CharField(max_length=100)),
                ('college_dates', models.CharField(max_length=20)),
                ('college_awards', models.CharField(max_length=100)),
                ('graduate_name', models.CharField(max_length=100)),
                ('graduate_address', models.CharField(max_length=100)),
                ('graduate_course', models.CharField(max_length=100)),
                ('graduate_dates', models.CharField(max_length=20)),
                ('graduate_awards', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='familyBackground_info',
            fields=[
                ('student_info_id', models.TextField(primary_key=True, serialize=False)),
                ('spouse_name', models.CharField(max_length=100)),
                ('spouse_birthdate', models.CharField(max_length=20)),
                ('spouse_educational', models.CharField(max_length=50)),
                ('spouse_occupation', models.CharField(max_length=50)),
                ('spouse_company', models.CharField(max_length=100)),
                ('spouse_company_address', models.CharField(max_length=100)),
                ('spouse_email', models.CharField(max_length=50)),
                ('spouse_children', models.CharField(max_length=5000)),
                ('father_name', models.CharField(max_length=100)),
                ('father_birthdate', models.CharField(max_length=20)),
                ('father_educational', models.CharField(max_length=50)),
                ('father_occupation', models.CharField(max_length=50)),
                ('father_company', models.CharField(max_length=100)),
                ('father_company_address', models.CharField(max_length=100)),
                ('father_email', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=20)),
                ('mother_educational', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('mother_company', models.CharField(max_length=100)),
                ('mother_company_address', models.CharField(max_length=100)),
                ('mother_email', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_relationship', models.CharField(max_length=20)),
                ('guardian_address', models.CharField(max_length=100)),
                ('guardian_occupation', models.CharField(max_length=50)),
                ('guardian_company', models.CharField(max_length=100)),
                ('guardian_company_address', models.CharField(max_length=100)),
                ('guardian_mobile', models.CharField(max_length=15)),
                ('guardian_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('lastname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('birthplace', models.CharField(max_length=30)),
                ('civil_status', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=6)),
                ('weight', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=30)),
                ('mobile_Number', models.CharField(max_length=30)),
                ('tel_Number', models.CharField(max_length=30)),
                ('present_address', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('created_date', models.CharField(max_length=30)),
            ],
        ),
    ]
